label = "GPU Linear"
dist = "L2Sqr"
gnd_path = "data/gnd_10000.local.bin"
index_cache = "data/gist_10000_pq_linear.local.bin"
bench_output = "data/bench_10000.local.toml"
gpu = true

[ef]
list = [0]

[algorithm.Linear]


[base]
dim = 960
data_type = "float32"
data_path = "data/gist_10000.local.bin"


[test]
dim = 960
data_type = "float32"
data_path = "data/gist_test.bin"
