label = "HNSW+PQ"
dist = "L2Sqr"
gnd_path = "data/gnd.local.bin"
index_cache = "data/gist_hnsw.local.bin"
bench_output = "data/bench.local.toml"

[ef.range]
start = 180
end = 600
step = 60

[algorithm.HNSW]
max_elements = 1000000
ef_construction = 200
M = 16

[PQ]
pq_cache = "data/gist_pq.local.bin"
dist = "L2Sqr"
n_bits = 4
m = 320
k_means_size = 10000
k_means_max_iter = 20
k_means_tol = 1e-6

[base]
dim = 960
data_type = "float32"
data_path = "data/gist.local.bin"


[test]
dim = 960
data_type = "float32"
data_path = "data/gist_test.bin"
