dist = "L2Sqr"
gnd_path = "data/gnd_10000.local.bin"
index_cache = "data/gist_10000_pq_linear.local.bin"

[ef]
list = [20, 200, 2000]

[algorithm.Linear]

[PQ]
pq_cache = "data/gist_10000_pq.local.bin"
dist = "L2Sqr"
n_bits = 4
m = 240
k_means_size = 1000
k_means_max_iter = 20
k_means_tol = 1e-6


[base]
dim = 960
data_type = "float32"
data_path = "data/gist_10000.local.bin"


[test]
dim = 960
data_type = "float32"
data_path = "data/gist_test.bin"
