distance = "L2Sqr"

[algorithm.HNSW]
num_elements = 1000000
max_elements = 1000000
ef_construction = 200
M = 16

[vec_data]
dim = 960
data_type = "float32"
data_path = "/root/datasets/gist/train.data"
size = 1000
