distance = "L2Sqr"

[algorithm.HNSW]
# max_elements = 1000000
max_elements = 1000
ef_construction = 200
M = 16

[vec_data]
dim = 960
data_type = "float32"
# data_path = "/root/datasets/gist/train.data"
# size = 1000
data_path = "data/example/gist_1000.bin"
