name: Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Python test
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv build
          uv run test-pyo3.py
